### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by JagadishaIncture** [stevdza-san/MessageBar-KMP#1]

**Comment by stevdza-san** [comment]
Thank you for your suggestion. I'll leave this issue opened, until I add this support.

**Comment by JagadishaIncture** [comment]
Can't we achive Timer in Kotlin so that we can avoid platform dependency?

**Comment by stevdza-san** [comment]
I've just pushed a new release v1.0.1, that supports Desktop target as well. :)
Yes, there's also a way to use Kotlin coroutines for that matter.

**Comment by JagadishaIncture** [comment]
Great Thanks

**Comment by JagadishaIncture** [comment]
I don't see code pushed.. it still Timer in Platform specific

**Comment by stevdza-san** [comment]
I didn't say I was going to use coroutines right now, I'm okay with a platform-specific implementation of Timer class. I don't see an issue with that choice. :)

**Comment by JagadishaIncture** [comment]
I was thinking if we remove Timer from Platform Specific impl and make write in CommanMain using Kotlin then it automaticaly support all platform including Web also.. we

**Comment by stevdza-san** [comment]
That's true. I'll consider that for some of the future releases.
