### ISSUE TITLE
font style

### ISSUE THREAD

**Issue by javad0470** [stevdza-san/MessageBar-KMP#2]
hi dear.
thank a lot for your useful library
please add fontStyle constructor as well

**Comment by stevdza-san** [comment]
Thanks for your suggestion, I'll leave this issue opened until the next release. :)

**Comment by javad0470** [comment]
thank a lot

**Comment by stevdza-san** [comment]
I've added extra parameters to customize the font of the Success/Error, as well as Copy Button text. You can update the version to v1.0.2. :)

**Comment by javad0470** [comment]
Such a wow, how fast! :)

**Comment by javad0470** [comment]
Sorry, I meant to write fontFamily instead of fontStyle.

**Comment by stevdza-san** [comment]
I'll add that one as well, expect it in the 1.0.3 release. I hope to push it at the end of the day. :)
