### ISSUE TITLE
compiler error when updating to 1.0.2

### ISSUE THREAD

**Issue by javad0470** [stevdza-san/MessageBar-KMP#3]
I encountered a weird compile error when I updated the project to version 1.0.2.

The issue is related to Drawable0 and the resource directory.

Errors (for all drawables and fonts):

e: file:///../composeapp/generated/resources/Drawable0.kt:43:5 No value passed for parameter 'offset'
e:file:///..composeApp/build/generated/compose/resourceGenerator/kotlin/barber_app/composeapp/generated/resources/Drawable0.kt:43:5 No value passed for parameter 'size'

When we revert to previous version 1.0.1, the issue is resolved.

**Comment by stevdza-san** [comment]
I've just used the 1.0.2 version and it works fine on my end. Try debug your app furthermore and see if you can get some more information?

**Comment by javad0470** [comment]
I try it in both macbook and windows system and I get same errors for drawble0 for each element

e: file:///P:/projects/app/composeApp/build/generated/compose/resourceGenerator/kotlin/test/composeapp/generated/resources/Drawable0.kt:46:5 No value passed for parameter 'offset'
e: file:///P:/projects/app/composeApp/build/generated/compose/resourceGenerator/kotlin/test/composeapp/generated/resources/Drawable0.kt:46:5 No value passed for parameter 'size'

**Comment by stevdza-san** [comment]
Have you updated your project to kotlin 2.0?

**Comment by javad0470** [comment]
no I dont

**Comment by stevdza-san** [comment]
Try updating to Kotln 2.0
