### ISSUE TITLE
Wasm support?

### ISSUE THREAD

**Issue by melod1n** [stevdza-san/MessageBar-KMP#4]

**Comment by JagadishaIncture** [comment]
@stevdza-san  any updates?

**Comment by stevdza-san** [comment]
@JagadishaIncture I'll start working on a WASM support next week probably. Since I haven't used that target so far I'll have to explore it a bit, but I hope it shouldn't be a problem. I'll close this issue once it's done. :)

**Comment by stevdza-san** [comment]
@JagadishaIncture I've just updated to the new version "1.0.6" that supports the wasm target as well. Feel free to check it out and let me know if it works well. :)

**Comment by JagadishaIncture** [comment]
@stevdza-san really appreciate your quick efforts.
